# Generated by Django 4.2 on 2024-11-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
