# Generated by Django 4.2 on 2024-11-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentaire', '0001_initial'),
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='evaluation.evaluation'),
        ),
    ]
